daktary:
  meta:
    title: 'MultiBào : Une multi-boite à outils'
    description: 'multiBàO permet aux animateurs de réseaux publiant des ressources participatives sur leurs sites web de pleinement les mutualiser.'

  ghRepos:
    - label: Pages pratiques
      account: multibao
      repo: contributions
      folder: pages
      
    - label: fiches multibao
      account: multibao
      repo: contributions
      folder: contributions
  
    - label: réseau transition
      account: reseautransitionwb
      repo: reseau_transition
      folder: contributions
  
    - label: démocratie ouverte
      account: alecoz
      repo: democratie_ouverte
      folder: contributions

  ghCss:
    ghContributionCss: css/contribs.css
    contribsList: css/contribs-list.css
    nav: css/nav.css
    reposList: css/repos-list.css
    mdMeta: css/md-meta.css

prose:
  rooturl: 'contributions'
  media: 'media'
  metadata:
    contributions:
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: "Contribution multibao"
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Ice breaker"
              value: "Ice breaker"
            - name: "Energizer"
              value: "Energizer"
            - name: "Organisation"
              value: "Organisation"
            - name: "Collaboration"
              value: "Collaboration"
            - name: "Citoyenneté"
              value: "Citoyenneté"
