prose:
  rooturl: 'contributions'
  media: 'media'
  metadata:
    contributions:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Ice breaker"
              value: "Ice breaker"
            - name: "Energizer"
              value: "Energizer"
            - name: "Organisation"
              value: "Organisation"
            - name: "Collaboration"
              value: "Collaboration"
            - name: "Citoyenneté"
              value: "Citoyenneté"
